# Generated by Django 5.2.5 on 2025-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processeddocument",
            name="error_details",
            field=models.JSONField(
                default=dict, help_text="Detailed error information for debugging"
            ),
        ),
        migrations.AddField(
            model_name="processeddocument",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of retry attempts"
            ),
        ),
    ]
