# Generated by Django 5.2.5 on 2025-09-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_add_error_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="processeddocument",
            name="source_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
